version: '3.7'

services:
    cotdb:
        image: postgres:latest
        container_name: cotdb
        env_file: .env
        expose:
            - 5432
        ports:
            - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
